#!/bin/python

import sys
import os

template = """#!/bin/bash
#SBATCH --time=01:10:00   # walltime in d-hh:mm or hh:mm:ss format
#SBATCH --job-name="mg {0}"
#SBATCH --output={0}.slurm_log
#SBATCH --error={0}.slurm_error
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=dm1@student.ubc.ca
#SBATCH --mem=1200  # max memory
echo Time: $(date)
echo "Starting makegalaxy for {0}. The job ID is $SLURM_JOBID."
echo $SLURM_JOBID >> job_ids
{1} {0}.txt
"""

exec_path = os.readlink('/home/dm1/bin/makegalaxy')

for fname in (os.path.splitext(s)[0] for s in sys.argv[1:]):
    with open(fname + ".makegalaxyjob.sh", "w") as f:
        f.write(template.format(fname, exec_path))
    os.system("sbatch " + fname + ".makegalaxyjob.sh")  
